# Generated by Django 4.2.16 on 2024-12-02 08:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="PostModel",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=120, verbose_name="title blog")),
                (
                    "content",
                    models.TextField(max_length=300, verbose_name="content blog"),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[("rf", "rofl"), ("bad", "bad"), ("gd", "good")],
                        max_length=120,
                    ),
                ),
                ("created_time", models.DateField(auto_now_add=True)),
            ],
        ),
    ]
