# Generated by Django 5.1.3 on 2024-12-02 11:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_alter_commentsmodel_created_time_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='postmodel',
            name='uid',
            field=models.UUIDField(default=1, verbose_name='post_uid'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='commentsmodel',
            name='content',
            field=models.TextField(unique=True, verbose_name='content'),
        ),
    ]
