# Generated by Django 5.1.3 on 2024-12-02 11:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_postmodel_uid_alter_commentsmodel_content'),
    ]

    operations = [
        migrations.AlterField(
            model_name='postmodel',
            name='uid',
            field=models.CharField(max_length=10),
        ),
    ]
