# Generated by Django 5.1.3 on 2024-12-02 11:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0008_alter_postmodel_uid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='postmodel',
            name='uid',
            field=models.CharField(max_length=10, null=True),
        ),
    ]
