# Generated by Django 5.1.3 on 2024-12-02 11:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0009_alter_postmodel_uid'),
    ]

    operations = [
        migrations.AddField(
            model_name='postmodel',
            name='flag_uid',
            field=models.CharField(default='True', max_length=10),
        ),
    ]
