# Generated by Django 5.1.3 on 2024-12-02 11:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0010_postmodel_flag_uid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='postmodel',
            name='uid',
            field=models.CharField(max_length=10, null=True, unique=True),
        ),
    ]
